### ISSUE TITLE
App should not crash when the specified navidrome server is down

### ISSUE THREAD

**Issue by accforgithubtest** [CraftWorksMC/Chora#11]
In a self-hosted set-up, I have set up navidrome server to automatically start up when there are requests / access, and shutdown if not in use for an hour or more.

I have installed chora app on android tv, and when I try to start up the app, it crashes without any errors. 

An ideal way to gracefully handle the issue where the configured navidrome server is down (or in case of mis-congurations / network issues / etc), would be to display an error to the user without crashing the app. That way it is clear to the user that something is wrong with the server, and not the app.

**Comment by CraftWorksMC** [comment]
This **should've** been already implemented and working.
![Screenshot from 2024-08-17 13-18-40](https://github.com/user-attachments/assets/da787954-f269-4a30-be3c-d42c8d32cb3f)
Can you share the app logs when it crashes? Could be as simple as some other network exception not being caught.

**Comment by accforgithubtest** [comment]
Thanks for your reply, it might be a case of uncaught exception.

Turns out I cannot access the logs because the the fire TV doesn't allow access to the apps folders.

**Comment by CraftWorksMC** [comment]
Should be fixed in 1.24.
If you still encounter this issue, re-open this issue and i'll look into it deeper
