### ISSUE TITLE
[Android TV] Better remote support for playback and back buttons

### ISSUE THREAD

**Issue by accforgithubtest** [CraftWorksMC/Chora#13]
I see from your readme that Android TV support is WIP, unsure if below items are already on your roadmap, and apologies if its already covered in your roadmap.

Currently when trying to use the app on android tv, I notice following issues, which I hope you will consider adding to your roadmap -

* The "focused element" keeps going back to the side bar whenever I switch to a new song. It would be great if the focus continued on the appropriate view showing the new song selected.

* Behavior of the back button is inconsistent. Sometimes it works by going back to the correct previous view but many time it simply goes to the side bar even though there are other views on the UI to which it should have ideally gone to.

**Comment by CraftWorksMC** [comment]
Fixed in release 1.24
