### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by accforgithubtest** [CraftWorksMC/Chora#14]
Please provide support for dark mode in the app which will make it great for just playing music with lyrics on the screen.

**Comment by Optekah** [comment]
Would love dark mode for the new Android TV pkg!

**Comment by lews-therin** [comment]
another upvote from my side!

**Comment by Optekah** [comment]
I almost forgot about Chora. 

Stopped using it pretty much immediately when I realized there was no dark mode. Might be okay on a mobile device, but on a 65" television at night, it's just eye-wateringly bright. Is this app still being developed or nah?

**Comment by lews-therin** [comment]
looking at the source, i think it has dark mode if it's set as the system theme, but my ShieldTv does not have the option to set it

**Comment by CraftWorksMC** [comment]
Added in release 1.25
