### ISSUE TITLE
[Android TV] Play and Shuffle Buttons Missing from Playlists

### ISSUE THREAD

**Issue by GavinL2001** [CraftWorksMC/Chora#17]
Albums have two buttons above the list of songs that allow for shuffled or non-shuffled playback. This feature is missing when viewing playlists.

View of playlist: 
![Screenshot_20240916-164714](https://github.com/user-attachments/assets/2a5ae157-5db1-4ff3-8687-400d1b900cd4)

View of Album:
![Screenshot_20240916-164809](https://github.com/user-attachments/assets/6a94191e-b267-48f3-bc3a-3b9d614a98bc)

**Comment by CraftWorksMC** [comment]
These screens will be unified in the next release. Currently the playlist system was under a bit of rework.

**Comment by CraftWorksMC** [comment]
Fixed in Release 1.24.1
