### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by programmer584** [CraftWorksMC/Chora#2]
Hey I really like the esthetics of your app and I am super excited to hear that android auto should also work (haven't tested it yet)! I have some tips/bugs for you, I hope I'm in the right place for this. 
- music stops but the media player claims to still be playing when closing the app completely
- ability to tap on the song playing (instead of having to swipe) to see it in full screen
- option to add songs to playlists
- titles on the app's home screen are too large causing text to overlap
- When launching the app, the media player is empty. It would be nicer if the song you last played is in the media player or just no media player.
- (chrome) cast support
- What might be a nice idea is to promote your app on a social media platform like reddit and ask for help in development from the community.
Greetings from belgium. Keep it up!

**Comment by CraftWorksMC** [comment]
- if you mean the notification, then Im already working on it.
- that was a feature a while ago, forgot to re-inplement it in the redesign.
- working on that, should be done soon
- huh, I'll see if I can scale the text down a bit
- I wanted to hide the now playing screen when no song was playing, having a bit of a hard time making it work nicely.
- this will come in future releases, not the focus right now.
- I made a few posts on Reddit already, don't want to spam the subreddits with this!
