### ISSUE TITLE
Add option to skip SSL certificate authority verification

### ISSUE THREAD

**Issue by accforgithubtest** [CraftWorksMC/Chora#9]
I am trying to login into a self hosted server with self-signed certificates and I get a "Status: Unknown error", while trying to use this app on a firetv stick max. (greedy amzn has removed the ability to add self-signed certificates to the underlying android OS certificate store on newer fire tv sticks.)

I see the same "Status: Unknown error" on phones / tablets / android tv.
So my best guess is that the self-signed certificate is causing the login failure.

Can you pls add a option to skip the certificate authority validations, and allow the use of self-signed certificates ? 

I came across your app via a comment on reddit when looking for navidrome clients, and I have to say that this looks promising in a land of many abandoned subsonic apps that do not work anymore, especially on android TV. Thanks for creating this neat looking project.

**Comment by CraftWorksMC** [comment]
Fixed in release 1.24
